name: Check for new manifest (Skip Check - TRUE)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Check for manifest update
        run: pnpm manifest:check
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PAT: ${{ secrets.PAT }}
          SKIP_CHECK: 'true'
